prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: monitoring
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        release: monitoring
    podMonitorNamespaceSelector: {}

grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30300
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
