apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.serviceType }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
      {{- if and (eq .Values.backend.serviceType "NodePort") .Values.backend.nodePort }}
      nodePort: {{ .Values.backend.nodePort }}
      {{- end }}
