apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: springboot
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.postgres.name }}:{{ .Values.postgres.servicePort }}/{{ .Values.postgres.db }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.user | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: FRAUD_DETECTION_SERVICE_URL
              value: http://{{ .Values.wiremock.name }}:{{ .Values.wiremock.servicePort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 40
            periodSeconds: 20
