base.url=http://localhost:4112  # ???? 4111
apiVersion=/api/v1/
admin.username=admin
admin.password=admin
admin.basic.auth=Basic YWRtaW46YWRtaW4=

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://192.168.0.16:3000
browser=chrome
browserSize=1920x1080